export const ROUTES = {
    LOGIN: "/",
    CONNECT_WALLET: "/connect-wallet",
    DASHBOARD: "/dashboard",
    PROFILE: "/profile",
    ROLE_MANAGEMENT: "/role-management",
    PDD_MANAGEMENT: "/pdd-management",
    PDD_DETAILS: "/pdd-details",
    ADD_PDD: "/add-pdd",
    USER_MANAGEMENT: "/user-management",
    ADD_USER: "/add-user",
    USER_DETAILS: "/user-details",
    EDIT_USER: "/edit-user-details",
    TOKEN_MANAGEMENT: "/token-management",
    TOKEN_DETAILS: "/token-deails",
    CREATE_TOKEN: "/create-token",
    PROJECT_MANAGEMENT: "/project-management",
    PROJECT_DETAILS: "/project-details",
    ADD_PROJECT: "/add-project",
    PROJECT_DETAILS_VIEW: "/project-details-view",
    COMPANY_DETAILS: "/company-details",
    COMPANIES: "/company-registerations",
    CREATE_COMPANY: "/create-company",
}